#!/bin/bash

archiveDir="$HOME/Documents/Projects/lainchan_archiver/archives/" #EDIT THIS TO CHANGE SAVE DIRECTORY

thread="$1"

if [ "$thread" = "" ]; then
  echo "How To: $0 [URL]"
  exit 1
fi

threadID=$(echo "$thread" | sed 's/http:\/\///' | cut -f 6 -d /)

cd $archiveDir

mkdir "$threadID"
cd "${threadID}"

echo -n "Getting thread..."
echo

while true; do
  if wget --spider -q "${thread}"
  then
    wget -r -q -k -E -N -nd -np lainchan.org/*/src/,lainchan.org/*/thumb/ "" ${thread}
  else
    echo "404 Not Found"
    break
  fi
done

echo "Done."

